CREATE TABLE games (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(255) UNIQUE,
                       genre VARCHAR(255),
                       price DOUBLE PRECISION,
                       stock INTEGER,
                       description TEXT
);